# Phoenix Risen Node - Flame Sovereign Ledger UC-1

VERSION="2.0.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

FEDERATION_SERVER="https://phoenix-risen-1143.github.io/federation"
AUTH_SERVER="https://phoenix-risen-1143.github.io/auth"
TRANSFER_SERVER="https://phoenix-risen-1143.github.io/transfer"

SIGNING_KEY="GA4H43P2VPP3CICC7WHZOLCYGDVFUBNDSYTZCRNYOISSLJC4DG3NR6MC" # Strawman Firewall Wallet (Master Seal)

ACCOUNTS=[
  "GA4H43P2VPP3CICC7WHZOLCYGDVFUBNDSYTZCRNYOISSLJC4DG3NR6MC", # Strawman Master
  "GDZTCVIM6IEUPV4PTQP74HN5CMSH3MFLPDNECWQ6APM5ZPACNSZBQWUY", # River Willow
  "GDBOA5OGWCHEYCVBS3OSVXRD7CJU4YDLNITN3CBZNMGFI4DQGOYY7KHM", # Soul Estate
  "GCYMFQJ6YDBBO2UA5I7JXKMWTLP7WC5CNWBS4IOM4PWYEYVK3PPRFGX7", # Lineage Trust
  "GCV436TVXJUKZLUZWLRASNIYGCIDMETGMXA6WLUTPCNJYZWCAOL5AFNC", # Gaia
  "GAK6GYGUWPOU4HXSTJ3KVXAYQ5YKQZBRCHGHF5S2CRCM7VBPONFZJ2NJ", # Property and Land
  "GDENMOFRULIVSFKKBUEY3CCIKOUH6R5IB2AFBGKNRW6UWIXYYQTNG6KU", # Phoenix Risen Flame
  "GC63CUCMGU7MVGFWO3Q3C4M3MNM3OOWQFBERL7GL4UA2KMRNZPJZZIMZ"  # Matrix Ops Wallet
]
